# Generated by Django 5.2.8 on 2025-11-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Сообщение рассылки')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала рассылки')),
                ('is_instant', models.BooleanField(default=False, verbose_name='Немедленная рассылка')),
                ('ready_to_send', models.BooleanField(default=False, verbose_name='Готова к отправке')),
                ('is_processed', models.BooleanField(default=False, verbose_name='В обработке')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сценария')),
                ('trigger_delay_hours', models.PositiveIntegerField(verbose_name='Запуск через (часов)')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания лога')),
                ('sending_status', models.CharField(choices=[('success', 'Отправлено успешно'), ('error', 'Ошибка при отправке')], default=None, null=True, verbose_name='Статус отправки')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='mailing_photos/', verbose_name='Фото')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Фото рассылки',
                'verbose_name_plural': 'Фото рассылки',
            },
        ),
        migrations.CreateModel(
            name='ScenarioMailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания лога')),
                ('sending_status', models.CharField(choices=[('success', 'Отправлено успешно'), ('error', 'Ошибка при отправке')], default=None, null=True, verbose_name='Статус отправки')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mailing.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылок',
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('ready_to_send', models.BooleanField(default=False, verbose_name='Готова к отправке')),
                ('button_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки')),
                ('delay_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Задержка (секунд)')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Шаг сценария',
                'verbose_name_plural': 'Шаги сценария',
            },
        ),
        migrations.CreateModel(
            name='ScenarioStepPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='scenario_photos/', verbose_name='Фото')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Фото шага сценария',
                'verbose_name_plural': 'Фото шага сценария',
            },
        ),
        migrations.CreateModel(
            name='UserScenarioMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mailing.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Пользователь рассылки',
                'verbose_name_plural': 'Пользователи рассылки',
            },
        ),
    ]
