# Generated by Django 5.2.8 on 2025-11-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariostepphoto',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.scenariostep', verbose_name='Шаг сценария'),
        ),
    ]
