# Generated by Django 5.2.8 on 2025-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingmedia',
            options={'verbose_name': 'Медиа-файл рассылки', 'verbose_name_plural': 'Медиа-файлы рассылки'},
        ),
        migrations.AlterModelOptions(
            name='scenariostepmedia',
            options={'verbose_name': 'Медиа-файл шага сценария', 'verbose_name_plural': 'Медиа-файлы шага сценария'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='text',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Сообщение рассылки'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='text',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Текст'),
        ),
    ]
