# Generated by Django 5.2.8 on 2025-11-26 13:53

import django.db.models.deletion
import server.apps.mailing.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_scenariostepphoto_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='mailingphoto',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mailing.mailing', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='mailingphoto',
            name='photo',
            field=models.ImageField(upload_to='mailing_photos/', validators=[server.apps.mailing.helpers.validate_photo_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='scenariostep',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='mailing.scenario', verbose_name='Сценарий'),
        ),
        migrations.AlterField(
            model_name='scenariostepphoto',
            name='photo',
            field=models.ImageField(upload_to='scenario_photos/', validators=[server.apps.mailing.helpers.validate_photo_size], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='scenariostepphoto',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mailing.scenariostep', verbose_name='Шаг сценария'),
        ),
    ]
