# Generated by Django 5.2.8 on 2025-11-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_scenario_is_active_alter_mailingphoto_mailing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscenariomailing',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mailing.scenariostep', verbose_name='Шаг сценария'),
        ),
    ]
