# Generated by Django 5.2.8 on 2025-11-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_userscenariomailing_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariostep',
            name='ready_to_send',
        ),
    ]
